### PR TITLE
add ability to use unix "socketPath" for establish connection

### PR DESCRIPTION
**Pull request by andrew-lyashenko**
Hi there!

Can you please accept my pull request to add ability to use "**socketPath**" option for mysql?

### CODE REVIEW

**Comment by mikermcneil** [comment]
@andrew-lyashenko thanks!  Would you mind writing up some sample usage?  e.g. what would I put in my `config/datastores.js` file in order to use this?

**Review by mikermcneil — CHANGES_REQUESTED** [review]
https://github.com/sailshq/machinepack-mysql/pull/11#issuecomment-388244861

**Comment by andrew-lyashenko** [comment]
Yes, sure. Here is an example config:

`config/datastores.js`

```javascript
default: {
    adapter: 'sails-mysql',
    user: 'db_user',
    password: 'db_password',
    database: 'db_name',
    socketPath: '/path/to/unix_socket'
}
```

**Comment by semy** [comment]
What is the status of this issue?

**Review by semy — APPROVED** [review]

**Comment by mikermcneil** [comment]
@semy @andrew-lyashenko Thanks for following up in Gitter y'all -- I set aside some time to review this weekend

**Review by mikermcneil — APPROVED** [review]

**Comment by mikermcneil** [comment]
@semy @andrew-lyashenko thanks!  I'll also get this change into https://github.com/mikermcneil/sails-sql -- I want to add some more configuration checks as well since mismatched db config is one of the most common thing folks new to the framework get confused about  (e.g. can't specify both `url` and `socketPath`).  Would welcome assistance on that front if y'all have a moment to take a look

**Comment by mikermcneil** [comment]
https://github.com/sailshq/machinepack-mysql/releases/tag/v3.1.0-0

**Comment by mikermcneil** [comment]
ok 👍 https://github.com/mikermcneil/sails-sql/commit/f7c5b960f013a3e04d8dd606aaa3b4eecd0d133c

**Pull request merged**
